/**
 * Guards `packages/core/mpc/types/**` files named `*_pb.ts` (protoc-gen-es output).
 *
 * Hand-written helpers live under `types/utils/` and are not matched by
 * `*_pb.ts`. Manual edits or accidental generator upgrades should trip this
 * suite: either the header shape breaks or the pinned per-version file counts
 * drift.
 */
import { readdirSync, readFileSync } from 'node:fs'
import { join, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const mpcDir = join(fileURLToPath(new URL('.', import.meta.url)), '..')
const typesDir = join(mpcDir, 'types')

const walk = (dir: string): string[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const path = join(dir, entry.name)

    if (entry.isDirectory()) {
      return walk(path)
    }

    return entry.isFile() ? [path] : []
  })

describe('generated protobuf headers (mpc/types, *_pb.ts)', () => {
  const files = walk(typesDir)
    .filter(abs => abs.endsWith('_pb.ts'))
    .filter(abs => !abs.includes(`types${sep}utils`))

  it('discovers only expected *_pb.ts files', () => {
    expect(files.length).toBeGreaterThan(0)
    for (const f of files) {
      expect(f.endsWith('_pb.ts')).toBe(true)
      expect(f.includes(`types${sep}utils`)).toBe(false)
    }
  })

  it('each file starts with protoc-gen-es banner + @generated from file + eslint-disable', () => {
    const genLine = /^\/\/ @generated by protoc-gen-es v[\d.]+ with parameter ".+"$/
    const fromLine = /^\/\/ @generated from file .+$/

    for (const file of files) {
      const text = readFileSync(file, 'utf8')
      const lines = text.split(/\r?\n/)
      expect(lines[0], file).toMatch(genLine)
      expect(lines[1], file).toMatch(fromLine)
      expect(lines[2], file).toBe('/* eslint-disable */')
    }
  })

  it('records current protoc-gen-es version groups (update counts when regenerating)', () => {
    const byVersion = new Map<string, number>()
    for (const file of files) {
      const first = readFileSync(file, 'utf8').split(/\r?\n/)[0]
      const m = first.match(/protoc-gen-es (v[\d.]+)/)
      expect(m, first).toBeTruthy()
      const v = m![1]
      byVersion.set(v, (byVersion.get(v) ?? 0) + 1)
    }

    expect(Object.fromEntries([...byVersion.entries()].sort())).toEqual({
      'v2.10.2': 6,
      'v2.11.0': 18,
    })
  })
})
