// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file vultisig/keygen/v1/keygen_message.proto (package vultisig.keygen.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { LibType } from "./lib_type_message_pb";
import { file_vultisig_keygen_v1_lib_type_message } from "./lib_type_message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keygen/v1/keygen_message.proto.
 */
export const file_vultisig_keygen_v1_keygen_message: GenFile = /*@__PURE__*/
  fileDesc("Cid2dWx0aXNpZy9rZXlnZW4vdjEva2V5Z2VuX21lc3NhZ2UucHJvdG8SEnZ1bHRpc2lnLmtleWdlbi52MSLyAQoNS2V5Z2VuTWVzc2FnZRISCgpzZXNzaW9uX2lkGAEgASgJEhYKDmhleF9jaGFpbl9jb2RlGAIgASgJEhQKDHNlcnZpY2VfbmFtZRgDIAEoCRIaChJlbmNyeXB0aW9uX2tleV9oZXgYBCABKAkSGgoSdXNlX3Z1bHRpc2lnX3JlbGF5GAUgASgIEhIKCnZhdWx0X25hbWUYBiABKAkSLQoIbGliX3R5cGUYByABKA4yGy52dWx0aXNpZy5rZXlnZW4udjEuTGliVHlwZRIOCgZjaGFpbnMYCCADKAkSFAoMaXNfdHNzX2JhdGNoGAkgASgIQlIKEnZ1bHRpc2lnLmtleWdlbi52MVo3Z2l0aHViLmNvbS92dWx0aXNpZy9jb21tb25kYXRhL2dvL3Z1bHRpc2lnL2tleWdlbi92MTt2MboCAlZTYgZwcm90bzM", [file_vultisig_keygen_v1_lib_type_message]);

/**
 * @generated from message vultisig.keygen.v1.KeygenMessage
 */
export type KeygenMessage = Message<"vultisig.keygen.v1.KeygenMessage"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string hex_chain_code = 2;
   */
  hexChainCode: string;

  /**
   * @generated from field: string service_name = 3;
   */
  serviceName: string;

  /**
   * @generated from field: string encryption_key_hex = 4;
   */
  encryptionKeyHex: string;

  /**
   * @generated from field: bool use_vultisig_relay = 5;
   */
  useVultisigRelay: boolean;

  /**
   * @generated from field: string vault_name = 6;
   */
  vaultName: string;

  /**
   * Default to GG20
   *
   * @generated from field: vultisig.keygen.v1.LibType lib_type = 7;
   */
  libType: LibType;

  /**
   * This field only used by KeyImport
   *
   * @generated from field: repeated string chains = 8;
   */
  chains: string[];

  /**
   * Initiator opts the ceremony into parallel ECDSA+EdDSA keygen
   *
   * @generated from field: bool is_tss_batch = 9;
   */
  isTssBatch: boolean;
};

/**
 * Describes the message vultisig.keygen.v1.KeygenMessage.
 * Use `create(KeygenMessageSchema)` to create a new message.
 */
export const KeygenMessageSchema: GenMessage<KeygenMessage> = /*@__PURE__*/
  messageDesc(file_vultisig_keygen_v1_keygen_message, 0);

