/**
 * Byte-parity unit tests for UTXO sighash primitives.
 *
 * Guards against silent drift in the hand-rolled BIP143 (BTC P2WPKH) and
 * SIGHASH_FORKID (BCH) implementations. Reference sighashes were generated
 * offline via bitcoinjs-lib's `hashForWitnessV0` — any divergence means the
 * signed raw tx changes and funds stop flowing.
 *
 * Fixture regeneration recipe (run in a throwaway Node env with
 * `npm i bitcoinjs-lib` installed):
 *
 *   const { Transaction } = require('bitcoinjs-lib')
 *   const tx = new Transaction()
 *   tx.version = 2
 *   // addInput(hash, index) — hash is little-endian Buffer
 *   tx.addInput(Buffer.from('11'.repeat(32), 'hex').reverse(), 0)
 *   tx.addInput(Buffer.from('22'.repeat(32), 'hex').reverse(), 1)
 *   // addOutput(scriptPubKey, value)
 *   tx.addOutput(Buffer.from('0014' + '22'.repeat(20), 'hex'), 120_000n)
 *   tx.addOutput(Buffer.from('0014' + '33'.repeat(20), 'hex'), 79_000n)
 *   const scriptCode = Buffer.from('76a914' + '11'.repeat(20) + '88ac', 'hex')
 *   const h0 = tx.hashForWitnessV0(0, scriptCode, 100_000n, Transaction.SIGHASH_ALL)
 *   const h1 = tx.hashForWitnessV0(1, scriptCode, 100_000n, Transaction.SIGHASH_ALL)
 *   // h0, h1 are the reference sighashes; paste as EXPECTED_* constants below.
 *
 * If these vectors ever fail, re-run the recipe rather than editing the
 * expected values blindly — the hand-rolled BIP143 in src/chains/utxo/tx.ts
 * must match bitcoinjs-lib byte-for-byte for funds to flow.
 */
import { describe, expect, it } from 'vitest'

import { getSighashBIP143, type UtxoInput } from '../../../src/chains/utxo/tx'

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  return out
}

function bytesToHex(b: Uint8Array): string {
  let s = ''
  for (let i = 0; i < b.length; i++) s += b[i]!.toString(16).padStart(2, '0')
  return s
}

// Shared fixture: 2-input, 2-output tx where the owner P2WPKH has
// pubKeyHash = 0x11*20, and the "to" script points at pubKeyHash 0x22*20.
const OWNER_PUBKEYHASH = hexToBytes('1111111111111111111111111111111111111111')

// Serialized outputs WITHOUT the leading varint count, matching
// `SighashBIP143Options.outputsRaw`. Generated by bitcoinjs-lib offline.
const OUTPUTS_RAW_HEX =
  'a086010000000000160014222222222222222222222222222222222222222268bf0000000000001600141111111111111111111111111111111111111111'

const INPUT_0: UtxoInput = {
  hash: 'aa'.repeat(32),
  index: 0,
  value: 150000n,
}
const INPUT_1: UtxoInput = {
  hash: 'bb'.repeat(32),
  index: 1,
  value: 100000n,
}

describe('utxo / getSighashBIP143 — BTC P2WPKH (reference: bitcoinjs-lib hashForWitnessV0)', () => {
  it('matches bitcoinjs-lib sighash for input 0 (SIGHASH_ALL, version=2)', () => {
    const actual = getSighashBIP143({
      inputs: [INPUT_0, INPUT_1],
      outputsRaw: hexToBytes(OUTPUTS_RAW_HEX),
      inputIndex: 0,
      pubKeyHash: OWNER_PUBKEYHASH,
    })
    expect(bytesToHex(actual)).toBe('5ae446de406771fc10094ecace1fec613f5f8de04319fa16246c00510e23e62a')
  })

  it('matches bitcoinjs-lib sighash for input 1 (SIGHASH_ALL, version=2)', () => {
    const actual = getSighashBIP143({
      inputs: [INPUT_0, INPUT_1],
      outputsRaw: hexToBytes(OUTPUTS_RAW_HEX),
      inputIndex: 1,
      pubKeyHash: OWNER_PUBKEYHASH,
    })
    expect(bytesToHex(actual)).toBe('dfe7e8cae2f26a8824c39970d412ba09078ef123cde9992be8404ab80c89f5b6')
  })

  it('throws on out-of-range inputIndex', () => {
    expect(() =>
      getSighashBIP143({
        inputs: [INPUT_0],
        outputsRaw: hexToBytes(OUTPUTS_RAW_HEX),
        inputIndex: 5,
        pubKeyHash: OWNER_PUBKEYHASH,
      })
    ).toThrow(/invalid inputIndex/)
  })
})

describe('utxo / getSighashBIP143 — BCH SIGHASH_FORKID (reference: bitcoinjs-lib hashForWitnessV0 with 0x41)', () => {
  // BCH uses BIP143-style sighash with sighashType=0x41 (SIGHASH_ALL | SIGHASH_FORKID).
  // Per the SDK spec, BCH tx version is 1.
  it('matches bitcoinjs-lib sighash for input 0 (sighashType=0x41, version=1)', () => {
    const BCH_OUTPUTS_RAW = hexToBytes(OUTPUTS_RAW_HEX) // reuse — identical shape
    const actual = getSighashBIP143({
      inputs: [INPUT_0],
      outputsRaw: BCH_OUTPUTS_RAW,
      inputIndex: 0,
      pubKeyHash: OWNER_PUBKEYHASH,
      version: 1,
      sighashType: 0x41,
    })
    expect(bytesToHex(actual)).toBe('dae1f8212a84dd5b5419e79c9cb4d05f3d01f9c8fafe69412fa1c2107d0400e3')
  })
})
