// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/dapp_metadata.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/dapp_metadata.proto.
 */
export const file_vultisig_keysign_v1_dapp_metadata: GenFile = /*@__PURE__*/
  fileDesc("Cid2dWx0aXNpZy9rZXlzaWduL3YxL2RhcHBfbWV0YWRhdGEucHJvdG8SE3Z1bHRpc2lnLmtleXNpZ24udjEiOwoMREFwcE1ldGFkYXRhEgwKBG5hbWUYASABKAkSCwoDdXJsGAIgASgJEhAKCGljb25fdXJsGAMgASgJQlQKE3Z1bHRpc2lnLmtleXNpZ24udjFaOGdpdGh1Yi5jb20vdnVsdGlzaWcvY29tbW9uZGF0YS9nby92dWx0aXNpZy9rZXlzaWduL3YxO3YxugICVlNiBnByb3RvMw");

/**
 * DAppMetadata identifies the dApp that asked for a signature. It is carried
 * by both KeysignPayload (transactions) and CustomMessagePayload (message
 * signing) so every co-signing device can show who is asking.
 *
 * All fields are untrusted: they are declared by the initiating device and
 * covered by no signature. Consumers must treat them as display-only and must
 * not use them for authorization or routing.
 *
 * @generated from message vultisig.keysign.v1.DAppMetadata
 */
export type DAppMetadata = Message<"vultisig.keysign.v1.DAppMetadata"> & {
  /**
   * Human-readable name of the dApp. Chosen by the dApp's page, so it is not
   * an identifier and not guaranteed unique. May be empty.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Origin of the requesting dApp: scheme and host, plus port when present
   * (e.g. "https://app.example.com"). No path, query or fragment.
   *
   * @generated from field: string url = 2;
   */
  url: string;

  /**
   * URL of the dApp's icon. Chosen by the dApp's page; consumers should
   * validate the scheme before fetching it. May be empty.
   *
   * @generated from field: string icon_url = 3;
   */
  iconUrl: string;
};

/**
 * Describes the message vultisig.keysign.v1.DAppMetadata.
 * Use `create(DAppMetadataSchema)` to create a new message.
 */
export const DAppMetadataSchema: GenMessage<DAppMetadata> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_dapp_metadata, 0);

