// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/erc20_approve_payload.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/erc20_approve_payload.proto.
 */
export const file_vultisig_keysign_v1_erc20_approve_payload: GenFile = /*@__PURE__*/
  fileDesc("Ci92dWx0aXNpZy9rZXlzaWduL3YxL2VyYzIwX2FwcHJvdmVfcGF5bG9hZC5wcm90bxITdnVsdGlzaWcua2V5c2lnbi52MSJVChNFcmMyMEFwcHJvdmVQYXlsb2FkEg4KBmFtb3VudBgBIAEoCRIPCgdzcGVuZGVyGAIgASgJEh0KFXJlc2V0X2FsbG93YW5jZV9maXJzdBgDIAEoCEJUChN2dWx0aXNpZy5rZXlzaWduLnYxWjhnaXRodWIuY29tL3Z1bHRpc2lnL2NvbW1vbmRhdGEvZ28vdnVsdGlzaWcva2V5c2lnbi92MTt2MboCAlZTYgZwcm90bzM");

/**
 * @generated from message vultisig.keysign.v1.Erc20ApprovePayload
 */
export type Erc20ApprovePayload = Message<"vultisig.keysign.v1.Erc20ApprovePayload"> & {
  /**
   * @generated from field: string amount = 1;
   */
  amount: string;

  /**
   * @generated from field: string spender = 2;
   */
  spender: string;

  /**
   * When true, every signer emits approve(spender, 0) at the payload nonce
   * before approve(spender, amount) at nonce + 1, and the main transaction
   * moves to nonce + 2. Set by the initiator only for tokens such as USDT
   * that revert on a non-zero -> non-zero approve while a stale allowance
   * remains. Defaults to false so payloads from older senders keep the
   * two-message shape.
   *
   * @generated from field: bool reset_allowance_first = 3;
   */
  resetAllowanceFirst: boolean;
};

/**
 * Describes the message vultisig.keysign.v1.Erc20ApprovePayload.
 * Use `create(Erc20ApprovePayloadSchema)` to create a new message.
 */
export const Erc20ApprovePayloadSchema: GenMessage<Erc20ApprovePayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_erc20_approve_payload, 0);

