// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/swapkit_swap_payload.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Coin } from "./coin_pb";
import { file_vultisig_keysign_v1_coin } from "./coin_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/swapkit_swap_payload.proto.
 */
export const file_vultisig_keysign_v1_swapkit_swap_payload: GenFile = /*@__PURE__*/
  fileDesc("Ci52dWx0aXNpZy9rZXlzaWduL3YxL3N3YXBraXRfc3dhcF9wYXlsb2FkLnByb3RvEhN2dWx0aXNpZy5rZXlzaWduLnYxItACChJTd2FwS2l0U3dhcFBheWxvYWQSLAoJZnJvbV9jb2luGAEgASgLMhkudnVsdGlzaWcua2V5c2lnbi52MS5Db2luEioKB3RvX2NvaW4YAiABKAsyGS52dWx0aXNpZy5rZXlzaWduLnYxLkNvaW4SEwoLZnJvbV9hbW91bnQYAyABKAkSGQoRdG9fYW1vdW50X2RlY2ltYWwYBCABKAkSDwoHdHhfdHlwZRgFIAEoCRISCgp0eF9wYXlsb2FkGAYgASgMEhYKDnRhcmdldF9hZGRyZXNzGAcgASgJEhwKD2luYm91bmRfYWRkcmVzcxgIIAEoCUgAiAEBEhEKBG1lbW8YCSABKAlIAYgBARIUCgxzdWJfcHJvdmlkZXIYCiABKAkSDwoHc3dhcF9pZBgLIAEoCUISChBfaW5ib3VuZF9hZGRyZXNzQgcKBV9tZW1vQlQKE3Z1bHRpc2lnLmtleXNpZ24udjFaOGdpdGh1Yi5jb20vdnVsdGlzaWcvY29tbW9uZGF0YS9nby92dWx0aXNpZy9rZXlzaWduL3YxO3YxugICVlNiBnByb3RvMw", [file_vultisig_keysign_v1_coin]);

/**
 * SwapKit-routed swap whose wire shape doesn't fit the EVM-typed
 * OneInchSwapPayload. Used for BTC PSBT, Sui PTB, TRON nested-object,
 * TON transfer array, and Cardano deposit-only flows returned by
 * POST /v3/swap on https://api.swapkit.dev.
 *
 * EVM and Solana SwapKit swaps continue to ride OneInchSwapPayload —
 * their /v3/swap shape matches OneInchQuote 1:1 and stays typed at the
 * proto layer. The `provider` string field on OneInchSwapPayload
 * disambiguates the aggregator at the peer.
 *
 * The flexibility here lives in tx_payload (a bytes passthrough opaque
 * to commondata) and tx_type (a string discriminator the cosigning
 * peer uses to dispatch to the right per-chain signer). Cosigning
 * peers MUST tolerate unknown tx_type values — drop through to an
 * "unsupported provider" UI rather than crashing the decode.
 *
 * @generated from message vultisig.keysign.v1.SwapKitSwapPayload
 */
export type SwapKitSwapPayload = Message<"vultisig.keysign.v1.SwapKitSwapPayload"> & {
  /**
   * Identity — same as every other swap payload.
   *
   * @generated from field: vultisig.keysign.v1.Coin from_coin = 1;
   */
  fromCoin?: Coin;

  /**
   * @generated from field: vultisig.keysign.v1.Coin to_coin = 2;
   */
  toCoin?: Coin;

  /**
   * Raw, in source-asset base units.
   *
   * @generated from field: string from_amount = 3;
   */
  fromAmount: string;

  /**
   * Human-readable, decimal-formatted expected output amount.
   *
   * @generated from field: string to_amount_decimal = 4;
   */
  toAmountDecimal: string;

  /**
   * SwapKit's `meta.txType` verbatim. Drives the peer-side dispatcher:
   *   "PSBT"     — tx_payload is a base64-decoded BTC PSBT
   *   "TRON"     — tx_payload is a JSON-encoded TronWeb transaction object
   *   "TON"      — tx_payload is a JSON-encoded [{address, amount}] array
   *   "SUI"      — tx_payload is a base64-decoded Sui PTB
   *   "CARDANO"  — tx_payload is empty (deposit-only flow);
   *                use target_address + from_amount to build a plain send
   *
   * Forward-compatible: new SwapKit chains land here without a commondata
   * bump, so long as the client SDK on each platform learns to decode the
   * new tx_type string. Peers that don't recognise a tx_type MUST fall
   * through to an "unsupported provider" UI rather than crash.
   *
   * @generated from field: string tx_type = 5;
   */
  txType: string;

  /**
   * Raw unsigned-transaction bytes returned by POST /v3/swap.
   *
   * Encoding by tx_type:
   *   PSBT     — base64-decoded PSBT bytes
   *   SUI      — base64-decoded Sui PTB bytes
   *   TRON     — UTF-8 bytes of the canonical JSON of the TronWeb object
   *   TON      — UTF-8 bytes of the canonical JSON of the transfer array
   *   CARDANO  — empty bytes (deposit-only flow)
   *
   * Bytes rather than string so binary payloads (PSBT, PTB) don't need
   * base64 round-tripping. Object-shaped payloads are JSON-encoded on
   * the initiator and decoded on the peer; canonical key ordering keeps
   * the digest deterministic.
   *
   * @generated from field: bytes tx_payload = 6;
   */
  txPayload: Uint8Array;

  /**
   * Deposit address on the source chain. For PSBT this duplicates info
   * also encoded inside tx_payload; for deposit-only chains (Cardano)
   * this is the only routing info available.
   *
   * @generated from field: string target_address = 7;
   */
  targetAddress: string;

  /**
   * THORChain-style inbound vault address. Optional — populated only for
   * routes that go through TC-style inbound monitoring. Rare in SwapKit
   * since the iOS / Android / SDK clients filter THORChain/Maya routes
   * out client-side, but kept for forward compatibility.
   *
   * @generated from field: optional string inbound_address = 8;
   */
  inboundAddress?: string;

  /**
   * Optional memo. SwapKit V3 returned null for every chain spike result
   * we captured; field exists for forward compatibility with providers
   * we haven't observed.
   *
   * @generated from field: optional string memo = 9;
   */
  memo?: string;

  /**
   * Sub-provider tag for the verify screen, e.g. "CHAINFLIP", "NEAR",
   * "GARDEN", "FLASHNET", "HARBOR". Verbatim from route.providers[0]
   * in the /v3/quote response.
   *
   * @generated from field: string sub_provider = 10;
   */
  subProvider: string;

  /**
   * SwapKit swap identifier — persisted for tracking and analytics.
   * Doesn't participate in signing. NOT accepted by POST /track —
   * tracking still keys off the broadcast hash + source chain id.
   *
   * @generated from field: string swap_id = 11;
   */
  swapId: string;
};

/**
 * Describes the message vultisig.keysign.v1.SwapKitSwapPayload.
 * Use `create(SwapKitSwapPayloadSchema)` to create a new message.
 */
export const SwapKitSwapPayloadSchema: GenMessage<SwapKitSwapPayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_swapkit_swap_payload, 0);

