// Objective-C API for talking to github.com/vultisig/go-wrappers/go-dkls/sessions Go package.
//   gobind -lang=objc github.com/vultisig/go-wrappers/go-dkls/sessions
//
// File is generated by gobind. Do not edit.

#ifndef __Session_H__
#define __Session_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * DklsDecodeKeyID decodes a key ID from a setup message.

Parameters:
  - setup: []byte - a byte slice containing the setup message from which the key ID will be decoded.

Returns:
  - []byte: the decoded key ID as a byte slice.
  - error: an error if the Rust function call fails or if any other issue occurs.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionDklsDecodeKeyID(NSData* _Nullable setup, NSError* _Nullable* _Nullable error);

/**
 * DklsDecodeMessage decodes a message from a setup message.

Parameters:
  - setup: []byte - a byte slice containing the setup message from which the message will be decoded.

Returns:
  - []byte: the decoded message as a byte slice.
  - error: an error if the Rust function call fails or if any other issue occurs.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionDklsDecodeMessage(NSData* _Nullable setup, NSError* _Nullable* _Nullable error);

/**
 * DklsDecodePartyName decodes the party name from a setup message for a specified index.

Parameters:
  - setup: []byte - a byte slice containing the setup message from which the party name will be retrieved.
  - index: uint32 - the index of the party whose name is to be decoded.

Returns:
  - []byte: the decoded party name as a byte slice.
  - error: an error if the Rust function call fails or if any other issue occurs.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionDklsDecodePartyName(NSData* _Nullable setup, long index, NSError* _Nullable* _Nullable error);

/**
 * DklsFinishSetupMsgNew generates a new DSG finish setup message

Parameters:
  - sessionID: []byte - session identifier.
  - messageHash: []byte - a hash of the message to be signed.
  - ids: []byte -  IDs of signers.

Returns:
  - []byte: generated setup message.
  - error: An error is returned if the Rust function call fails or if any other issue is encountered.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionDklsFinishSetupMsgNew(NSData* _Nullable sessionID, NSData* _Nullable messageHash, NSData* _Nullable ids, NSError* _Nullable* _Nullable error);

// skipped function DklsHdSessionFinish with unsupported parameter or return types


// skipped function DklsHdSessionFree with unsupported parameter or return types


// skipped function DklsHdSessionFromSetup with unsupported parameter or return types


// skipped function DklsHdSessionInputMessage with unsupported parameter or return types


// skipped function DklsHdSessionMessageReceiver with unsupported parameter or return types


// skipped function DklsHdSessionOutputMessage with unsupported parameter or return types


/**
 * DklsHdSetupMsgNew generates a new HD derivation setup message.

Parameters:
  - keyID: []byte - key identifiers used in the derivation process.
  - chainPath: []byte - derivation path specifying the HD node to derive.
  - ids: []byte - null-delimited participant identifiers.

Returns:
  - []byte: generated setup message.
  - error: An error is returned if the Rust function call fails or if any issue occurs.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionDklsHdSetupMsgNew(NSData* _Nullable keyID, NSData* _Nullable chainPath, NSData* _Nullable ids, NSError* _Nullable* _Nullable error);

// skipped function DklsKeyExportReceiverFinish with unsupported parameter or return types


// skipped function DklsKeyExportReceiverInputMessage with unsupported parameter or return types


// skipped function DklsKeyExportReceiverNew with unsupported parameter or return types


// skipped function DklsKeyExporter with unsupported parameter or return types


// skipped function DklsKeyImportInitiatorNew with unsupported parameter or return types


// skipped function DklsKeyImporter with unsupported parameter or return types


// skipped function DklsKeyMigrateSessionFromSetup with unsupported parameter or return types


// skipped function DklsKeyRefreshSessionFromSetup with unsupported parameter or return types


// skipped function DklsKeygenSessionFinish with unsupported parameter or return types


// skipped function DklsKeygenSessionFree with unsupported parameter or return types


// skipped function DklsKeygenSessionFromSetup with unsupported parameter or return types


// skipped function DklsKeygenSessionInputMessage with unsupported parameter or return types


// skipped function DklsKeygenSessionMessageReceiver with unsupported parameter or return types


// skipped function DklsKeygenSessionOutputMessage with unsupported parameter or return types


/**
 * DklsKeygenSetupMsgNew creates a setup message for key generation.

Parameters:
  - threshold: int - The threshold number of keys required for key generation.
  - keyID: []byte - A pointer to a byte slice containing the key identifiers.
  - ids: []byte - A pointer to a byte slice containing participant IDs for the keygen process.

Returns:
  - []byte: The generated keygen setup message as a byte slice.
  - error: An error is returned if the Rust function call fails or if any other issue is encountered.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionDklsKeygenSetupMsgNew(long threshold, NSData* _Nullable keyID, NSData* _Nullable ids, NSError* _Nullable* _Nullable error);

// skipped function DklsKeyshareChainCode with unsupported parameter or return types


// skipped function DklsKeyshareDeriveChildPublicKey with unsupported parameter or return types


// skipped function DklsKeyshareFree with unsupported parameter or return types


// skipped function DklsKeyshareFromBytes with unsupported parameter or return types


// skipped function DklsKeyshareKeyID with unsupported parameter or return types


// skipped function DklsKeysharePublicKey with unsupported parameter or return types


// skipped function DklsKeyshareToBytes with unsupported parameter or return types


// skipped function DklsKeyshareToRefreshBytes with unsupported parameter or return types


// skipped function DklsPresignFromBytes with unsupported parameter or return types


// skipped function DklsPresignSessionID with unsupported parameter or return types


// skipped function DklsPresignToBytes with unsupported parameter or return types


// skipped function DklsQcSessionFinish with unsupported parameter or return types


// skipped function DklsQcSessionFromSetup with unsupported parameter or return types


// skipped function DklsQcSessionInputMessage with unsupported parameter or return types


// skipped function DklsQcSessionMessageReceiver with unsupported parameter or return types


// skipped function DklsQcSessionOutputMessage with unsupported parameter or return types


// skipped function DklsQcSetupMsgNew with unsupported parameter or return types


// skipped function DklsRefreshShareFromBytes with unsupported parameter or return types


// skipped function DklsRefreshShareToBytes with unsupported parameter or return types


// skipped function DklsSignSessionFinish with unsupported parameter or return types


// skipped function DklsSignSessionFree with unsupported parameter or return types


// skipped function DklsSignSessionFromSetup with unsupported parameter or return types


// skipped function DklsSignSessionInputMessage with unsupported parameter or return types


// skipped function DklsSignSessionMessageReceiver with unsupported parameter or return types


// skipped function DklsSignSessionOutputMessage with unsupported parameter or return types


/**
 * DklsSignSetupMsgNew generates a new signing setup message

Parameters:
  - keyIDs: []byte - key identifiers used in the signing process.
  - chainPath: []byte - chain path.
  - messageHash: []byte - a hash of the message to be signed.
  - ids: []byte -  IDs of signers.

Returns:
  - []byte: generated setup message.
  - error: An error is returned if the Rust function call fails or if any other issue is encountered.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionDklsSignSetupMsgNew(NSData* _Nullable keyID, NSData* _Nullable chainPath, NSData* _Nullable messageHash, NSData* _Nullable ids, NSError* _Nullable* _Nullable error);

#endif
