// Objective-C API for talking to github.com/vultisig/go-wrappers/go-schnorr/sessions Go package.
//   gobind -lang=objc github.com/vultisig/go-wrappers/go-schnorr/sessions
//
// File is generated by gobind. Do not edit.

#ifndef __Session_H__
#define __Session_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * SchnorrDecodeKeyId decodes a key ID from a setup message.

Parameters:
  - setup: []byte - a byte slice containing the setup message from which the key ID will be decoded.

Returns:
  - []byte: the decoded key ID as a byte slice.
  - error: an error if the Rust function call fails or if any other issue occurs.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionSchnorrDecodeKeyID(NSData* _Nullable setup, NSError* _Nullable* _Nullable error);

/**
 * SchnorrDecodeMessage decodes a message from a setup message.

Parameters:
  - setup: []byte - a byte slice containing the setup message from which the message will be decoded.

Returns:
  - []byte: the decoded message as a byte slice.
  - error: an error if the Rust function call fails or if any other issue occurs.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionSchnorrDecodeMessage(NSData* _Nullable setup, NSError* _Nullable* _Nullable error);

/**
 * SchnorrDecodePartyName decodes the party name from a setup message for a specified index.

Parameters:
  - setup: []byte - a byte slice containing the setup message from which the party name will be retrieved.
  - index: uint32 - the index of the party whose name is to be decoded.

Returns:
  - []byte: the decoded party name as a byte slice.
  - error: an error if the Rust function call fails or if any other issue occurs.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionSchnorrDecodePartyName(NSData* _Nullable setup, long index, NSError* _Nullable* _Nullable error);

/**
 * SchnorrDecodeSessionId decodes a session ID from a setup message.

Parameters:
  - setup: []byte - a byte slice containing the setup message from which the session ID will be decoded.

Returns:
  - []byte: the decoded session ID as a byte slice.
  - error: an error if the Rust function call fails or if any other issue occurs.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionSchnorrDecodeSessionID(NSData* _Nullable setup, NSError* _Nullable* _Nullable error);

// skipped function SchnorrKeyExportReceiverFinish with unsupported parameter or return types


// skipped function SchnorrKeyExportReceiverInputMessage with unsupported parameter or return types


// skipped function SchnorrKeyExportReceiverNew with unsupported parameter or return types


// skipped function SchnorrKeyExporter with unsupported parameter or return types


// skipped function SchnorrKeyImportInitiatorNew with unsupported parameter or return types


// skipped function SchnorrKeyImporterNew with unsupported parameter or return types


// skipped function SchnorrKeyMigrateSessionFromSetup with unsupported parameter or return types


// skipped function SchnorrKeyRefreshSessionFromSetup with unsupported parameter or return types


// skipped function SchnorrKeygenSessionFinish with unsupported parameter or return types


// skipped function SchnorrKeygenSessionFree with unsupported parameter or return types


// skipped function SchnorrKeygenSessionFromSetup with unsupported parameter or return types


// skipped function SchnorrKeygenSessionInputMessage with unsupported parameter or return types


// skipped function SchnorrKeygenSessionMessageReceiver with unsupported parameter or return types


// skipped function SchnorrKeygenSessionOutputMessage with unsupported parameter or return types


/**
 * SchnorrKeygenSetupMsgNew creates a setup message for key generation.

Parameters:
  - threshold: uint32 - t parameter for the MPC threshold protocol: t minimum nodes are needed to sign. t-1 degree polynomial.
  - keyID: []byte - unique identifier of all keyshares: currently hash of public key.
  - ids: []byte - human readable party identifiers.

Returns:
  - []byte: The generated keygen setup message as a byte slice.
  - error: An error is returned if the Rust function call fails or if any other issue is encountered.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionSchnorrKeygenSetupMsgNew(int32_t threshold, NSData* _Nullable keyID, NSData* _Nullable ids, NSError* _Nullable* _Nullable error);

// skipped function SchnorrKeyshareChainCode with unsupported parameter or return types


// skipped function SchnorrKeyshareFromBytes with unsupported parameter or return types


// skipped function SchnorrKeyshareKeyID with unsupported parameter or return types


// skipped function SchnorrKeysharePublicKey with unsupported parameter or return types


// skipped function SchnorrKeyshareToBytes with unsupported parameter or return types


// skipped function SchnorrQcSessionFinish with unsupported parameter or return types


// skipped function SchnorrQcSessionFromSetup with unsupported parameter or return types


// skipped function SchnorrQcSessionInputMessage with unsupported parameter or return types


// skipped function SchnorrQcSessionMessageReceiver with unsupported parameter or return types


// skipped function SchnorrQcSessionOutputMessage with unsupported parameter or return types


// skipped function SchnorrQcSetupMsgNew with unsupported parameter or return types


// skipped function SchnorrSignSessionFinish with unsupported parameter or return types


// skipped function SchnorrSignSessionFree with unsupported parameter or return types


// skipped function SchnorrSignSessionFromSetup with unsupported parameter or return types


// skipped function SchnorrSignSessionInputMessage with unsupported parameter or return types


// skipped function SchnorrSignSessionMessageReceiver with unsupported parameter or return types


// skipped function SchnorrSignSessionOutputMessage with unsupported parameter or return types


/**
 * SchnorrSignSetupMsgNew generates a new signing setup message

Parameters:
  - keyIDs: []byte - key identifiers used in the signing process.
  - chainPath: []byte - chain path.
  - messageHash: []byte - a hash of the message to be signed.
  - ids: []byte -  IDs of signers.

Returns:
  - []byte: generated setup message.
  - error: An error is returned if the Rust function call fails or if any other issue is encountered.
 */
FOUNDATION_EXPORT NSData* _Nullable SessionSchnorrSignSetupMsgNew(NSData* _Nullable keyID, NSData* _Nullable chainPath, NSData* _Nullable message, NSData* _Nullable ids, NSError* _Nullable* _Nullable error);

#endif
